# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://thundermeet.netlify.app/event-time/302")
 
    self.driver.find_element(By.ID, "login_userId").click()
    self.driver.find_element(By.ID, "login_userId").send_keys("1234")
    self.driver.find_element(By.ID, "login_password").click()
    self.driver.find_element(By.ID, "login_password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn:nth-child(1) > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > div > .ScheduleSelector__Wrapper-sc-1ke4ka2-0 .ScheduleSelector__GridCell-sc-1ke4ka2-2:nth-child(26) > div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > div > .ScheduleSelector__Wrapper-sc-1ke4ka2-0 .ScheduleSelector__GridCell-sc-1ke4ka2-2:nth-child(26) > div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > div > .ScheduleSelector__Wrapper-sc-1ke4ka2-0 .ScheduleSelector__GridCell-sc-1ke4ka2-2:nth-child(26) > div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > div > .ScheduleSelector__Wrapper-sc-1ke4ka2-0 > .ScheduleSelector__Grid-sc-1ke4ka2-1").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div > .ScheduleSelector__Wrapper-sc-1ke4ka2-0 .typography__Text-jsvm8p-1:nth-child(58)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container > .ant-btn > span:nth-child(2)").click()
  
actor = TestUntitled()
actor.setup_method("foo")
actor.test_untitled()
print("Sleep for 5 seconds")
# time.sleep(5)
# actor.save_html()
# actor.get_title()
print("all steps completed.")