# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestForgetPassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_forgetPassword(self):
    self.driver.get("http://localhost:3000/")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn-default > span").click()
    self.driver.find_element(By.ID, "login_user_id").click()
    self.driver.find_element(By.ID, "login_user_id").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn-round").click()
  def save_html(self, fn = "signup_test_output1.html"):
    self.html = self.driver.execute_script("return document.body.innerHTML")
    with open(fn, 'w', encoding = 'utf-8') as fh:
        fh.write(self.html)

actor = TestForgetPassword()
actor.setup_method("foo")
actor.test_forgetPassword()
print("Sleep for 5 seconds")
time.sleep(5)
actor.save_html()
# actor.get_title()
print("all steps completed.")
