# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditprofilegroup():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editprofilegroup(self):
    self.driver.get("https://thundermeet.netlify.app/")
    self.driver.set_window_size(1054, 742)
    self.driver.find_element(By.ID, "login_userId").click()
    self.driver.find_element(By.ID, "login_userId").send_keys("1234")
    self.driver.find_element(By.ID, "login_password").click()
    self.driver.find_element(By.ID, "login_password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn:nth-child(1) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".anticon-form path:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input").send_keys("test1")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".submit-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".add path:nth-child(3)").click()
    self.driver.find_element(By.ID, "groupName").click()
    self.driver.find_element(By.ID, "groupName").send_keys("test event2")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-selector").click()
    self.driver.find_element(By.ID, "groupName").send_keys("test event3")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-selection-overflow").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-selection-overflow").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-item-option-active > .ant-select-item-option-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-item-option-active > .ant-select-item-option-content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn-primary > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn-primary > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.close()
  

actor = TestEditprofilegroup()
actor.setup_method("foo")
actor.test_editprofilegroup()
print("Sleep for 5 seconds")
time.sleep(5)
# actor.get_title()
print("all steps completed.")